defaults:
    - hydra/job_logging: colorlog
    - hydra/hydra_logging: colorlog
training:
    # reproduce
    random_seed: 1
    num_gpus_per_node: 2
    # Mixed Precision
    fp16: true
    fp16_opt_level: "O1" # O0 to disable fp16
    # Optimization
    learning_rate: 1e-5
    gradient_accumulation_steps: 1
    max_grad_norm: 1.0 # disabled when negative
    optimizer: "AdamW"
    batch_size: 1024
    total_num_epochs: 10
saving:
    # when saving.iterations_interval and saving.seconds_interval
    # are both negative, save the models for every epoch
    iterations_interval: -1
    seconds_interval: 10 # disabled when iterations_interval > 1
    # checkpointer
    num_checkpoints_to_keep: 1
    keep_checkpoint_every_num_seconds: 3600
    resume_mode: true
logging:
    color: true
    level: "DEBUG"    
    iterations_interval: -1 # disabled when negative
    seconds_interval: 1 # disabled when `log_iterations_interval` is set