preempt:
    instance_name: qywu-torchfly
    loop_interval: 60 # how many seconds for the interval to check if the instance is preempted. 
    task_duration: 60 # how many hours for this task
    start_time: 2020-02-25 21:09